// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('myApp', ['ngRoute', 'ui.bootstrap', 'localytics.directives', 'angular-underscore', 'myApp.filters', 'myApp.services', 'myApp.directives', 'myApp.controllers']);

  app.config(function($routeProvider) {
    $routeProvider.when('/view1', {
      templateUrl: 'partials/partial1.html',
      controller: 'MyCtrl1'
    });
    $routeProvider.when('/view2', {
      templateUrl: 'partials/partial2.html',
      controller: 'MyCtrl2'
    });
    return $routeProvider.otherwise({
      redirectTo: '/view1'
    });
  });

}).call(this);
