// Generated by CoffeeScript 1.6.3
(function() {
  var createValidatorLinker, module;

  createValidatorLinker = function(directiveName, isValid) {
    return function(scope, elm, attrs, ctrl) {
      return ctrl.$parsers.unshift(function(viewValue) {
        var viewValueIsValid;
        viewValueIsValid = isValid(viewValue, scope);
        ctrl.$setValidity(directiveName, viewValueIsValid || false);
        if (viewValueIsValid) {
          return viewValue;
        } else {
          return void 0;
        }
      });
    };
  };

  module = angular.module('myApp.directives', ['myApp.services']);

  module.directive('inContainer', function() {
    return {
      require: 'ngModel',
      restrict: 'A',
      scope: {
        container: '=inContainer'
      },
      link: createValidatorLinker('inContainer', function(viewValue, scope) {
        return _.contains(scope.container, viewValue);
      })
    };
  });

}).call(this);
