// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  module = angular.module('myApp.services', []);

  module.value('version', '0.1');

  module.value('minYear', '2007');

  module.value('maxYear', '2015');

  module.value('minPermitNumber', 0);

  module.value('maxPermitNumber', 1000);

  module.service('ParkingRecords', function() {
    return {
      "new": function() {
        return {
          numberOfPermits: 0,
          hasPlacard: true,
          isHandicapped: true,
          isWheelchairAccessible: true,
          isReturn: true,
          year: 2007,
          firstPermitNumber: 0,
          lastPermitNumber: 0,
          lot: 'CG',
          type: 'this',
          paymentType: 'chicken',
          sport: 'football',
          department: 'nuclear engineering',
          contact: ''
        };
      }
    };
  });

  module.service('Lots', function() {
    return {
      all: function() {
        return ['AA', 'CG', 'GT'];
      }
    };
  });

  module.service('Types', function() {
    return {
      all: function() {
        return ['this', 'that', 'the other'];
      }
    };
  });

  module.service('PaymentTypes', function() {
    return {
      all: function() {
        return ['cash', 'check', 'card', 'chicken'];
      }
    };
  });

  module.service('Sports', function() {
    return {
      all: function() {
        return ['football', 'basketball', 'lady vols', 'luge'];
      }
    };
  });

  module.service('Departments', function() {
    return {
      all: function() {
        return ['nuclear engineering', 'EECS', 'BOS'];
      }
    };
  });

  module.service('Persons', function() {
    var mockPersons;
    mockPersons = [
      {
        id: '1234',
        netId: 'ashly',
        firstName: 'Ashly',
        lastName: 'Pearson',
        email: 'ashry@utk.edu'
      }
    ];
    return {
      all: function() {
        return mockPersons;
      },
      "new": function() {
        return {
          id: '',
          netId: '',
          firstName: '',
          lastName: '',
          email: ''
        };
      },
      create: function(person) {
        mockPersons.push(person);
        return person;
      },
      read: function() {},
      update: function(person) {},
      "delete": function() {}
    };
  });

  module.factory('CurrentParkingRecord', function() {
    return {
      numberOfPermits: 0,
      hasPlacard: true,
      isHandicapped: true,
      isWheelchairAccessible: true,
      isReturn: true,
      year: 2007,
      firstPermitNumber: 0,
      lastPermitNumber: 0,
      lot: 'CG',
      type: 'this',
      paymentType: 'chicken',
      sport: 'football',
      department: 'nuclear engineering',
      contact: ''
    };
  });

}).call(this);
